# Generated by Django 4.1 on 2022-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exit",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exit",
            name="longitude",
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exit",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="tracks_lat",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="tracks_long",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
